version: '3.8'
services:
  calendar-service:
    build: ./calendar-service
 
    ports:
      - "8000:8000"
    networks:
      - life-network
  ui-service:
    build: ./ui-service
    environment:
      - REACT_APP_CALENDAR_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    networks:
      - life-network
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./Jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    networks:
      - life-network
volumes:
  jenkins_home:
networks:
  life-network:
    driver: bridge