version: '3.8'
services:
  calendar-service:
    build: ./calendar-service
    ports:
      - "8000:8000"
    networks:
      - life-network
  ui-service:
    build: ./ui
    ports:
      - "3000:3000"
    networks:
      - life-network
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    networks:
      - life-network
volumes:
  jenkins_home:
networks:
  life-network:
    driver: bridge