apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-deployment
  labels:
    app: calendar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
      - name: calendar-service
        image: registry.gitlab.com/guy-livne/calendar-service:v1.0.0
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: gitlab-registry-secret